### ISSUE TITLE
Cannot re-calling relay_header anymore.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-offchain-tools#2]
https://github.com/darwinia-network/darwinia/issues/214

So the proof and relay tools need to be fixed and updated, especially after child process get killed.

**Comment by clearloop** [comment]
We can relay one header for once,  in `cmd-tools`, the second time we trying to relay a same header which is on darwinia, will raise an error at 

https://github.com/darwinia-network/darwinia-offchain-tools/blob/d0548c56445f046c0e45c55df3a6b932d06f58d9/cmd-tools/src/utils.ts#L91

: telling you `header exists`

---

### This will not happen

This will not happen in `cmd-tools`:

+ in `static mode` proof tests, `cmd-tools` will reset header before we relay a new one
+ in `dynamic mode` proof tests, `cmd-tools` will relay header based on the bestheaderhash on darwinia
+ in `relay` service, `cmd-tools` will check the bestheaderhash and auto-restart when this happens
